# Generated by Django 5.2.7 on 2026-03-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark Purple (Default)'), ('light', 'Light Mode'), ('one-dark', 'One Dark')], default='dark', max_length=20),
        ),
    ]
