# Generated by Django 5.2.7 on 2026-03-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='story_audio/'),
        ),
    ]
